### PR TITLE
fix: pin the version of the golang cookbook

### PR DESCRIPTION
**Pull request by fcuny-rbx**
Some cookbook depending on this cookbook are failing their unit tests
with the following error:

```
[2022-08-08T22:21:40+00:00] FATAL: Chef::Exceptions::CookbookChefVersionMismatch: Cookbook 'golang' version '5.4.0' depends on chef version [">= 15.3"], but the running chef version is 14.14.25
```

By pinning the version of the cookbook we will be able to run the tests.
This is already set in the tests for this cookbook (see
`test/fixtures/policies/default.rb`).

### CODE REVIEW

**Comment by fcuny-rbx** [comment]
Related to https://github.com/Roblox/rblx_telegraf/pull/33 - and it's possible this is not the right approach, let me know if I should be handling this differently.

**Review by garywangblox — APPROVED** [review]
Sounds good to me :)

**Review by roberteckert — APPROVED** [review]
LGTM.

**Comment by stan2474** [comment]
true

**Pull request merged**
